### ISSUE TITLE
All data gone!

### ISSUE THREAD

**Issue by Goldensyrup** [alienfamily/scanyourboxes#20] opened 2022-10-07 11:16 UTC
I was adding things to an old but empty box. Added one item, okay, added second item, and first item seemed to have disappeared.
Went back to "My Boxes", pulled down to refresh, and... everything went. I now have no data at all, just the prompt to create your first box.

I am still signed in. I have not tried to synchronise by importing from iCloud, as I don't know how old that data is!

What's happened?

Also, for a while now, when adding text to item names, it is clearly in a white font, as it doesn't display, until one clicks save and then you see it.

**Comment by alienfamily** [comment] 2022-10-10 07:49
Hi,

The issue on text color is fixed on the last release (v3.0.3).

Concerning your data, you can have an empty list when:

1. you have no boxes and you create a new account and subscribe.
2. your subscription period has expired. When your subscription expired we delete all your boxes from our server.
3. you are logged in with another account that the one you previously used

What you experienced with the first item disappearing could be related to a network issue but it should not remove all your boxes.

Could you send your account email on scanyourboxes@gmail.com?
I will check your subscription status.

**Comment by alienfamily** [comment] 2022-10-10 14:48
Thanks for all the infos your provided via email.

The issue is related to the search feature that enabled the pull to refresh on the boxes list.
It will be fixed in the next release.

**Closed as completed** 2023-04-07 12:58 UTC
